apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::015869558882:role/styleflow-eks-cluster-role
      username: styleflow-cluster-role
      groups:
        - system:masters
