apiVersion: apps/v1
kind: Deployment
metadata:
  name: styleflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: styleflow-app
  template:
    metadata:
      labels:
        app: styleflow-app
    spec:
      containers:
      - name: styleflow-app-container
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} # GitHub Actions가 이 부분을 바꿔치기할 것입니다.
        ports:
        - containerPort: 8080