apiVersion: apps/v1
kind: Deployment
metadata:
  name: styleflow-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: styleflow-app
  template:
    metadata:
      labels:
        app: styleflow-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: styleflow-app-container
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
