# k8s/patch-probe.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: styleflow-deployment
spec:
  template:
    spec:
      containers:
      - name: styleflow-app-container
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
